### ISSUE TITLE
"TypeError: Cannot call method 'log' of undefined" && "Unrecognized command --help"

### ISSUE THREAD

**Issue by timoxley** [zetlen/fenestrate#2]
Fenestrate currently dies when trying to call `--help`.

```
> fenestrate --help
Unrecognized command --help

/usr/local/lib/node_modules/fenestrate/fenestrate.js:293
  log(helpText);
  ^
TypeError: Cannot call method 'log' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/fenestrate/fenestrate.js:293:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/fenestrate/bin/fenestrate:7:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by zetlen** [comment]
Bear in mind that the comments don't need a `--` in front of them!
