### ISSUE TITLE
"SyntaxError: Unexpected end of input" on `fenestrate make`

### ISSUE THREAD

**Issue by timoxley** [zetlen/fenestrate#3]
Dies when calling `fenestrate make`.

```
> fenestrate make
Reading installed dependencies for /Users/timoxley/Projects/some-project
Successfully read dependencies.

undefined:4515
              "resolved": "https://registry.npmjs.org/d
                                                       ^
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /usr/local/lib/node_modules/fenestrate/fenestrate.js:164:18
    at ChildProcess.exithandler (child_process.js:654:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
```

Let me know if you need more information.

**Comment by zetlen** [comment]
How strange! It looks like the JSON output from NPM is truncated. If you run "npm install --json" in that directory, does it output valid JSON or does it exit early for some reason?

**Comment by tboyce** [comment]
Getting the same thing here.
```
$ fenestrate make                      
Reading installed dependencies for /home/tboyce/npm-test
Successfully read dependencies.
undefined:4534
                      "resolved": "https://registry.npmjs.o
                                                           

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /usr/lib/node_modules/fenestrate/fenestrate.js:164:18
    at ChildProcess.exithandler (child_process.js:210:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by zetlen** [comment]
Tell you what, I ought to deprecate this library. NPM3 actually does a pruning and flattening thing that obviates this little tool. What version of NPM are you using, @tboyce?

**Comment by tboyce** [comment]
Using 2.11.3.
Looking into the possibility of upgrading to 3.x now.

**Comment by zetlen** [comment]
Hey folks, I'm so sorry about the long delay here. I suspect that you had a large dep tree and that https://github.com/zetlen/fenestrate/pull/6 fixes your issue. I'm releasing a new version shortly--I'll leave this issue open in case v0.4.0 doesn't fix it.
